image:
  repository: go-app
  tag: latest

replicaCount: 1

service:
  type: NodePort
  port: 80          
  nodePort: 32362   

ingress:
  enabled: true
  className: nginx
  host: go-app.local
  path: /

